version: 2.1
jobs:
  gcc_u22_04:
    docker:
      - image: ubuntu:jammy
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt update
            export DEBIAN_FRONTEND=noninteractive
            apt install software-properties-common -yq
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            apt install build-essential g++ cmake libbox2d-dev libmrpt-dev -yq
            apt install protobuf-compiler libprotobuf-dev libzmq3-dev -yq
            apt install git -yq
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Generate cmake files
          command: |
            cmake -S . -B build
      - run: make -C build
      # - run: CTEST_OUTPUT_ON_FAILURE=1 make test -C build
  clang_u22_04:
    docker:
      - image: ubuntu:jammy
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt update
            export DEBIAN_FRONTEND=noninteractive
            apt install software-properties-common -yq
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            apt install build-essential clang cmake libbox2d-dev libmrpt-dev -yq
            apt install protobuf-compiler libprotobuf-dev libzmq3-dev -yq
            apt install git -yq
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Generate cmake files
          environment:
            CC: /usr/bin/clang
            CXX: /usr/bin/clang++
          command: |
            cmake -S . -B build
      - run: make -C build
      #- run: CTEST_OUTPUT_ON_FAILURE=1 make test -C build
workflows:
  version: 2
  build:
    jobs:
      - gcc_u22_04
      - clang_u22_04
